@hostname = localhost
@port = 3001
@personId = 636458e0a4ca9d7794bdf534
@missingPersonId = 6
@host = http://{{hostname}}:{{port}}

###

GET {{host}}/api/persons/{{personId}} HTTP/1.1
Accept: application/json

###

GET {{host}}/api/persons/{{missingPersonId}} HTTP/1.1
Accept: application/json